### ISSUE TITLE
Failed due to HTTP 404 of cljstyle

### ISSUE THREAD

**Issue by hatappo** [DeLaGuardo/setup-clojure#100]
Example GitHub Actions yaml.

```yaml
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.2
        with:
          cli: 1.11.1.1435
          clj-kondo: latest
          cljstyle: latest
```

## Cause

The latest release of cljstyle seems to use the naming
`cljstyle_${version}_linux_amd64.zip`
instead of 
`cljstyle_${version}_linux.zip`

https://github.com/greglook/cljstyle/releases/tag/0.16.626
