### ISSUE TITLE
404 on leiningen download (gitea)

### ISSUE THREAD

**Issue by recumbentbirder** [DeLaGuardo/setup-clojure#107]
I'm using the attached actions file, trying to run on a Linux runner. (I added installation of zstd, because I got complaints about missing zstd around my problem ...). When it comes to installing Leiningen, I get the following error, regardless if I run the runner from binary or via docker.

`::debug::Failed to download from "https://raw.githubusercontent.com/technomancy/leiningen/2.9.1/bin/lein". Code(404) Message(Not Found)`

The URL is perfectly fine though when trying to fetch either on my machine directly, or in a runner's docker container.

Any idea on how to solve this?

Thanks for your software!
/christoph

```yaml
name: Example Workflow for Clojure

on: [push]

jobs:

  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: install zstd
        run: apt-get update && apt-get install -y zstd

      - name: Checkout
        uses: actions/checkout@v3

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          lein: 2.9.1                  # Leiningen
          
      # Optional step:
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-

      - name: Get leiningen version
        run: lein -v
```
