### ISSUE TITLE
I fail to pin the version of `cli`

### ISSUE THREAD

**Issue by PEZ** [DeLaGuardo/setup-clojure#127]
Hello. Thanks for providing this action!

In hunting an issue with building an app, ,y workflow file tries to pin the `cli` version:

```yaml
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.1.1543
          bb: latest
```

But then when `clojure` is invoked, I get this:

```
Clojure tools not yet in expected location: /home/runner/.deps.clj/1.12.1.1550/ClojureTools/clojure-tools-1.12.1.1550.jar
Downloading https://github.com/clojure/brew-install/releases/download/1.12.1.1550/clojure-tools.zip to /home/runner/.deps.clj/1.12.1.1550/ClojureTools/clojure-tools.zip
Unzipping /home/runner/.deps.clj/1.12.1.1550/ClojureTools/clojure-tools.zip ...
Successfully installed clojure tools!
```

Which is the latest version, as of this writing.

Am I holding things wrong?
