### ISSUE TITLE
Update `actions/setup-java` version in readme

### ISSUE THREAD

**Issue by frenchy64** [DeLaGuardo/setup-clojure#31]
According to the [upgrade guide](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md), we might want to update this part of the README:

```yml
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
```

to

```yml
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
```

I haven't tested this yet, but I often copy this template for new builds.
