### ISSUE TITLE
docs imply cli does not support 'latest'

### ISSUE THREAD

**Issue by lread** [DeLaGuardo/setup-clojure#46]
Hiya! Thanks so much for these great GitHub Action setup tools!

One small thing I noticed is that the README gives this example:

```
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen
          boot: 2.8.3     # or use 'latest' to always provision latest version of boot
          bb: 0.7.8       # or use 'latest' to always provision latest version of babashka
```

Which to me implies that `cli:` does not support `'latest'`, but maybe it does?
