### ISSUE TITLE
boot support for MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [DeLaGuardo/setup-clojure#57]
Hi,

is there a technical reason why `boot` is not supported for MS-Windows? `boot.exe` appears to behave similar to `boot.sh`, both available from the same source at https://github.com/boot-clj/boot-bin/releases.

```yml
      - name: Get boot version
        # Boot is not yet available for windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: boot -V
```

Thanks
