### ISSUE TITLE
Clojure install error after boot.exe/cache update

### ISSUE THREAD

**Issue by ikappaki** [DeLaGuardo/setup-clojure#59]
Hi,

I'm getting the following error with latest mainline after #58

```
Run DeLaGuardo/setup-clojure@master

Leiningen found in cache C:\hostedtoolcache\windows\Leiningen\2.9.1-9-0\x64
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -c "iwr -useb download.clojure.org/install/win-install-1.10.3.1013.ps1 | iex"
C:\hostedtoolcache\windows\Java_Zulu_jdk\8.0.342-7\x64\bin\java.exe -cp dist JavaVersion
Error: Could not find or load main class JavaVersion
Error: The process 'C:\hostedtoolcache\windows\Java_Zulu_jdk\8.0.342-7\x64\bin\java.exe' failed with exit code 1
```

to reproduce, use the following action

```
jobs:
  cross-platform:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0


      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.3.1013
          lein: 2.9.1
          bb: 0.8.157
          boot: 2.8.3
```

can't spot something wrong with the action def ...

corresponding java install log output
```
Run actions/setup-java@v3

Trying to resolve the latest version from remote
Resolved latest version as 8.0.342+7

Trying to download...

Downloading Java 8.0.342+7 (Zulu) from https://cdn.azul.com/zulu/bin/zulu8.64.0.15-ca-jdk8.0.342-win_x64.zip ...

Extracting Java archive...

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\4cbbb769-8ec7-4225-9a81-2dcbc3e3bcff', 'D:\a\_temp\7ccfa74a-c337-4dcb-a07f-a4af3d532fb6')"

Java 8.0.342+7 was downloaded

Setting Java 8.0.342+7 as the default
Java configuration:
  Distribution: zulu
  Version: 8.0.342+7
  Path: C:\hostedtoolcache\windows\Java_Zulu_jdk\8.0.342-7\x64
Creating settings.xml with server-id: github
Writing to C:\Users\runneradmin\.m2\settings.xml
```

Thanks
