### ISSUE TITLE
Consider using the new officially sanctioned clj-msi when installing clojure on Windows

### ISSUE THREAD

**Issue by lread** [DeLaGuardo/setup-clojure#65]
Hiya! 

I am excited to see support for `deps.exe` (as `clojure.exe`) on Windows.
Thanks so much for adding that as a feature!

The current README suggests selecting via:
```
  cmd-exe-workaround: 'latest' # Replaces `clojure` with `deps.clj` on Windows
```

But the source code sez `cmd-exe-workaround` is deprecated https://github.com/DeLaGuardo/setup-clojure/blob/3199aaaa9cf140bcb7a5f36a72d1aa42658ee991/action.yml#L17-L24

But I don't know what a "unified cli input" is.

Let's say I have a matrix build for macOS, Windows, and Linux, how should I select `deps.exe` (as `clojure.exe`) for windows?

**Comment by DeLaGuardo** [comment]
The latest version got a fix to run clojure tools deps on windows the same way as on other platforms. https://github.com/DeLaGuardo/setup-clojure/blob/main/.github/workflows/smoke-tests.yml#L31-L52

**Comment by lread** [comment]
Thanks for the reply!

By cli, you mean the [Clojure official Windows PowerShell module](https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows), right?

Can I still use [borkdude's deps.exe (renamed to clojure) on Windows](https://github.com/borkdude/deps.clj)?

Or are you saying that `cli` automatically uses deps.exe on Windows?

(Sorry if the answer is obvious, I'm feeling a little not-so-bright here! 🙂)

**Comment by DeLaGuardo** [comment]
Right, getLatestDepsClj is not used anymore. Instead, when you use input `cli: %version%` for windows platform, it will install official Windows PowerShell Module into the directory visible for powershell and pwsh (default shell for github action runner on windows). That means previously required option `shell: powershell` is not needed anymore. Run step using `clojure` command line will recognise correctly where binary is installed without additional options.

```yml
jobs:
  run-clojure-cli:
    strategy:
      matrix:
        # note all three available platforms
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          cli: 1.10.1.693

      # step uses clojure command is the same across all platforms
      - name: Execute clojure code
        run: clojure -e "(+ 1 1)"
```
