### ISSUE TITLE
"Bad Credentials" fetching clj-kondo

### ISSUE THREAD

**Issue by rome-user** [DeLaGuardo/setup-clojure#87]
I am trying to run the following workflow on Gitea/Forgejo actions.

```yaml
name: clj-kondo checks
on: [push]
jobs:
  self-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up clj-kondo
      uses: https://github.com/DeLaGuardo/setup-clojure@master
      with:
        clj-kondo: latest

    - name: Run clj-kondo
      run: clj-kondo --lint src
```

This steps exactly at the "Set up clj-kondo" step with the following logs

```
[clj-kondo checks/self-lint] [DEBUG] executing remote job container: [node /var/run/act/actions/https---github.com-DeLaGuardo-setup-clojure@master/dist/index.js]
[clj-kondo checks/self-lint]   🐳  docker exec cmd=[node /var/run/act/actions/https---github.com-DeLaGuardo-setup-clojure@master/dist/index.js] user= workdir=
[clj-kondo checks/self-lint] [DEBUG] Exec command '[node /var/run/act/actions/https---github.com-DeLaGuardo-setup-clojure@master/dist/index.js]'
[clj-kondo checks/self-lint] [DEBUG] Working directory '/data/.cache/act/bunseki/backend-model'
[clj-kondo checks/self-lint]   ❗  ::error::Bad credentials
[clj-kondo checks/self-lint]   | ::error::Bad credentials
[clj-kondo checks/self-lint]   ❌  Failure - Main Set up clj-kondo
[clj-kondo checks/self-lint] exitcode '1': failure
```
