### ISSUE TITLE
API Rate Limit exceeded errors

### ISSUE THREAD

**Issue by dgtized** [DeLaGuardo/setup-clojure#96]
On several projects using setup-clojure I've been encountering occasional failures from API rate limits.

As example:
```
Run DeLaGuardo/setup-clojure@12.1
  with:
    cli: latest
    bb: latest
    github-token: ***
    invalidate-cache: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64

API rate limit exceeded for $IPADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Unfortunately, it's not clear from the error what documentation needs to be checked in order to authenticate for a higher rate limit.

It looks like this was previously encountered in #40 but was then removed in #45. From the error message I can't be sure, but I wonder if the fetch step for CLI is passing the token correctly but the corresponding logic for fetching babashka is not using a token?

I'm also using caching, but I'm curious if using latest instead of a specific version might be forcing cache misses.

Thank you very much for this very useful github action, hopefully we can find a solution to address the sporadic failures.
